### ISSUE TITLE
ngrok cert issues

### ISSUE THREAD

**Issue by zendoodles** [palantirnet/the-vagrant#37]
TASK [ngrok : Download ngrok] **************************************************
fatal: [uw-stout]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for bin.equinox.io:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine or you can install the `urllib3`, `pyOpenSSL`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error."}
                to retry, use: --limit @/Users/stephanju/Sites/uw-stout/provisioning/uw-stout.retry
 
PLAY RECAP *********************************************************************
uw-stout                   : ok=19   changed=4    unreachable=0    failed=1   
 
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
➜  uw-stout git:(develop) ✗ 
 
How do we either ignore cert check or get a CA cert installed?

**Comment by becw** [comment]
This was specific to a particular project -- and when I handed that off to the client, I removed the ngrok portion from the custom provisioning. If we need to include ngrok on a future project, we may run into this again, but based on how much we used it there (not much) I don't think that we will.
