### ISSUE TITLE
Generate local certs with SAN

### ISSUE THREAD

**Issue by froboy** [palantirnet/the-vagrant#50]
In order for local certs to validate, they need to have a SAN (subjectAltName) entry. This takes a little rejiggering, but this post https://security.stackexchange.com/a/183973 makes it look a lot easier. Once openssl 1.1.1 is released we should add `sudo apt-get update && sudo apt-get install --only-upgrade openssl` to the https task and then use the awesome new commands in that post.

**Comment by becw** [comment]
Resolved by #51 -- this will be included in the next release.
